print("Hello World")
print("What is you name?")
myname = input()
print(" Its is nice to meet you, " + myname)
print("The length of your name is:")
print(len(myname))
print("What is you age?")
myAge = input()
print("You will be " + str(int(myAge) + 1) + " in a year.")
